#if defined(OPENRTS_BOARD_SPARKFUN_LORA_GATEWAY)
// SparkFun LoRa Gateway (w/RFM69 module)
#define OPENRTS_RADIO_TYPE_RFM69
#define OPENRTS_RADIO_MISO 12
#define OPENRTS_RADIO_MOSI 13
#define OPENRTS_RADIO_CS   16
#define OPENRTS_RADIO_SCK  14
#define OPENRTS_RADIO_RST  27
#define OPENRTS_RADIO_DATA 32
#define OPENRTS_BUTTON_1   0
#define OPENRTS_LED        17
#elif defined(OPENRTS_BOARD_TTGO_LORA32_V21)
// LILYGO TTGO LoRa32 (V2.1)
#define OPENRTS_RADIO_TYPE_SX1278
#define OPENRTS_RADIO_MISO 19
#define OPENRTS_RADIO_MOSI 27
#define OPENRTS_RADIO_CS   18
#define OPENRTS_RADIO_SCK  5
#define OPENRTS_RADIO_RST  23
#define OPENRTS_RADIO_DATA 32
#define OPENRTS_LED        25
#elif defined(OPENRTS_BOARD_HELTEC_WIFI_LORA_32_V2)
// Heltec WiFi LoRa 32 (V2)
#define OPENRTS_RADIO_TYPE_SX1278
#define OPENRTS_RADIO_MISO 19
#define OPENRTS_RADIO_MOSI 27
#define OPENRTS_RADIO_CS   18
#define OPENRTS_RADIO_SCK  5
#define OPENRTS_RADIO_RST  14
#define OPENRTS_RADIO_DATA 34
#define OPENRTS_BUTTON_1   0
#define OPENRTS_LED        25
#elif defined(OPENRTS_BOARD_ADAFRUIT_M0_RFM69)
#define OPENRTS_RADIO_TYPE_RFM69
#define OPENRTS_RADIO_MISO 22
#define OPENRTS_RADIO_MOSI 23
#define OPENRTS_RADIO_CS   8
#define OPENRTS_RADIO_SCK  24
#define OPENRTS_RADIO_RST  4
#define OPENRTS_RADIO_DATA 0
#define OPENRTS_LED        13
#elif defined(OPENRTS_BOARD_ADAFRUIT_32U4_RFM69)
#define OPENRTS_RADIO_TYPE_RFM69
#define OPENRTS_RADIO_MISO 14
#define OPENRTS_RADIO_MOSI 16
#define OPENRTS_RADIO_CS   8
#define OPENRTS_RADIO_SCK  15
#define OPENRTS_RADIO_RST  4
#define OPENRTS_RADIO_DATA 0
#define OPENRTS_LED        13
#elif defined(OPENRTS_BOARD_RASPBERRY_PI_RFM69_BONNET)
#define OPENRTS_RADIO_TYPE_RFM69
#define OPENRTS_BUTTON_1     5
#define OPENRTS_BUTTON_2     6
#define OPENRTS_BUTTON_3     12
#define OPENRTS_BUTTON_4     13
#define OPENRTS_RADIO_DATA   24
#define OPENRTS_SPI_DEVICE   "/dev/spidev0.1"
#define OPENRTS_GPIOD_DEVICE "/dev/gpiochip0"
#elif defined(OPENRTS_BOARD_RASPBERRY_PI_RFM96_BONNET)
#define OPENRTS_RADIO_TYPE_SX1278
#define OPENRTS_BUTTON_1     5
#define OPENRTS_BUTTON_2     6
#define OPENRTS_BUTTON_3     12
#define OPENRTS_BUTTON_4     13
#define OPENRTS_RADIO_DATA   24
#define OPENRTS_SPI_DEVICE   "/dev/spidev0.1"
#define OPENRTS_GPIOD_DEVICE "/dev/gpiochip0"
#endif