name: Build Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - doxygen/Doxyfile
      - .github/workflows/build_docs.yml

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docs
        uses: mattnotmitt/doxygen-action@edge
        with:
            doxyfile-path: 'doxygen/Doxyfile'

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs