name: Build Arduino Example Apps

# Here we tell GitHub to run the workflow when a commit
# is pushed or a Pull Request is opened.
on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - examples/arduino/**
      - .github/workflows/build_arduino_examples.yml

jobs:
  build-examples:

    strategy:
      matrix:
        example: ["sniffer", "remote", "receiver"]
        board: ["esp32:esp32:sparkfun_lora_gateway_1-channel", "adafruit:avr:feather32u4"]

        # Representative ESP32 board
        include:
          - board: "esp32:esp32:sparkfun_lora_gateway_1-channel"
            cores: "esp32:esp32"
            board-defines: "-DOPENRTS_BOARD_SPARKFUN_LORA_GATEWAY -DOPENRTS_BUTTON_2=0 -DOPENRTS_BUTTON_3=0 -DOPENRTS_BUTTON_4=0"
        
        # Representative AVR board
        include:
          - board: "adafruit:avr:feather32u4"
            cores: "arduino:avr adafruit:avr"
            board-defines: "-DOPENRTS_BOARD_ADAFRUIT_32U4_RFM69 -DOPENRTS_BUTTON_1=0 -DOPENRTS_BUTTON_2=0 -DOPENRTS_BUTTON_3=0 -DOPENRTS_BUTTON_4=0"

    runs-on: ubuntu-latest

    steps:
      # First of all, we clone the repo using the `checkout` action.
      - name: Checkout
        uses: actions/checkout@v3

      # We use the `arduino/setup-arduino-cli` action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli config add board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.cores }}

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: |
          arduino-cli compile \
            --fqbn ${{ matrix.board }} \
            --build-property compiler.cpp.extra_flags="${{ matrix.board-defines }}" \
            --library="$PWD" \
            examples/arduino/${{matrix.example}}
