name: Build Example Apps

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - examples/**
      - platformio.ini
      - .github/workflows/build_examples.yml

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - example: examples/espidf/remote
            env: featheresp32-espidf
          - example: examples/espidf/sniffer
            env: featheresp32-espidf
          - example: examples/raspberry-pi/remote
            env: linux
          - example: examples/raspberry-pi/sniffer
            env: linux

    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install libgpiod
      run: sudo apt-get install -y libgpiod-dev
    - name: Run PlatformIO
      run: |
        pio run -e ${{ matrix.env }}
      env:
        PLATFORMIO_BUILD_FLAGS:
        PLATFORMIO_SRC_DIR: ${{ matrix.example }}